[#ftl]
[@b.head/]
[@b.grid items=tutoredStds var="tutoredStd"]
  [@b.row]
    [@b.boxcol /]
    [@b.col property="std.user.code" title="学号" width="10%"/]
    [@b.col property="std.user.name" title="姓名" width="10%"/]
    [@b.col width="10%" property="activity.date" title="日期"]${(tutoredStd.activity.date?string('yyyy-MM-dd'))?default('')}[/@]
    [@b.col width="15%" title="时间"]${tutoredStd.activity.beginAt! }-${tutoredStd.activity.endAt }[/@]
    [@b.col width="15%" property="activity.subject" title="活动名称（类别）"/]
    [@b.col width="10%" property="activity.teacher.user.name" title="组织教师"/]
    [@b.col width="10%" property="activity.location" title="地点"/]
  [/@]
[/@]

[@b.foot/]
