[#ftl]
[@b.head/]
[@b.toolbar title="选择“${activity.subject }”的学生名单"]bar.addBack();[/@]
[@b.grid items=tutoresStds var="tutoresStd"]
  [@b.row]
      [@b.col property="std.user.code" title="学号" width="10%"/]
      [@b.col property="std.user.name" title="姓名" width="10%"/]
      [@b.col property="std.person.gender.name"title="性别" width="10%"/]
      [@b.col property="std.state.grade" title="年级" width="10%"/]
      [@b.col property="std.state.department.name" title="管理院系" width="20%"/]
      [@b.col property="std.state.major.name" title="专业" width="20%"]${(tutoresStd.std.state.major.name)!} ${(tutoresStd.std.state.direction.name)!}[/@]
      [@b.col property="std.state.squad.name"  title="班级" width="20%"/]
  [/@]
[/@]
[@b.foot/]
